name: EventLoggerForIM
description: Logging utility to send messages to a Slack/Discord webhook.
version: 1.1.6
api-version: 1.16
author: HideTheMonkey
main: com.hidethemonkey.elfim.ELPlugin
softdepend:
  - LuckPerms
commands:
  elfs:
    description: Set Slack related configurations
    usage: /elfs [enable | disable <key>] [set token | channel | avatarUrl | bustUrl <value>]
    permission: ELFIM.elfimadmin
permissions:
  ELFIM.elfimadmin:
    description: Allows admin to configure ELFIM
    default: false
